### ISSUE TITLE
Workshop Privacy Curtains

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#128]
If I work with the Workshop Door open, both curious and nefarious `people` can see all of the Toys!
This is _obviously highly_ undesirable. 
So I'm thinking of addressing it by using the "spare" blackout curtains. 

# Todo

+ [x]  Measure the width of the curtains
+ [x] Cut the 10mm plywood mounting 
+ [x] Laser-cut 8 mounting circles from 10mm plywood scraps
+ [x] Measure & mount the circles to the mounting panel
+ [x] Mount the panel on the wall outside the workshop to ensure that the curtains _almost_ touch but don't drag on the ground
+ [x] Test visibility with Garage Door open. 
+ [x] Repeat for 2 other sections

**Comment by nelsonic** [comment]
Installed privacy curtains covering the entrance:

![IMG_9896](https://github.com/dwyl/workshop/assets/194400/41cf4dbc-57fe-4e6a-936a-f571a973c299)

From the road, *none* of the inside is visible now. 

![IMG_9897](https://github.com/dwyl/workshop/assets/194400/583f0b50-beb3-440a-a017-a2be9e1a93aa)

this will *enforce* privacy on the workmen who don’t care about our tools being seen/scouted.

**Comment by nelsonic** [comment]
From the inside, the gaps between the curtains allow me/us to easily see out to notice movement and allow air flow:

![IMG_9899](https://github.com/dwyl/workshop/assets/194400/488d7112-2c89-44f1-b8da-2e67b75c5c5b)

I’m satisfied with this for now. 👌
