### ISSUE TITLE
Feat: Hook/Hanger for Swing Ball Rackets 🎾 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#129]
At present there is nowhere to hook & store the swingball rackets when they are not in use.  So they often end up laying around and look untidy/messy:

![IMG_9937](https://github.com/dwyl/workshop/assets/194400/c310e931-ae8a-4c43-b4ac-3c77460a230c)

I try to hang them on the post:
![IMG_9936](https://github.com/dwyl/workshop/assets/194400/1376c165-35c4-4646-96ba-133befff1be4)

this kinda works:

![IMG_9932](https://github.com/dwyl/workshop/assets/194400/39f5a1a8-c191-4d7a-8dd6-1a4bdb91e739)

but it’s not a foolproof _system_ that other people can consistently follow. So nobody else does it and _especially_ not the children who play with it. 👦👧 🎾 

I think I can _easily_ design and make a child-friendly hook/hanger in the workshop in T25m that will encourage _all_ to hang up the rackets when not in use. 💭

# Todo

+ [ ] measure the diameter of the post
+ [ ] sketch the design I have in my head
+ [ ] recreate the sketch in LightBurn
+ [ ] laser cut the parts from scrap 10mm plywood
+ [ ] sand down any rough/sharp edges on the belt sander or by hand
+ [ ] assemble with wood glue, clamps and Brad nails; no screws! 
+ [ ] Finish with outdoor varnish for weather durability
+ [ ] Mount with Velcro cable-tidy with 👦 
+ [ ] Explain to all that’s where the outdoor rackets belong

**Comment by nelsonic** [comment]
Just walked past the Swingball and the rackets were on the floor:

![image](https://github.com/dwyl/workshop/assets/194400/f6bbdabc-84f0-4192-accd-c10c2d4eb1c9)

It's kinda ridiculous how much it bugs me to see things out-of-place. 

Went straight to the workshop to get my callipers to measure the diameter of the pole:
![image](https://github.com/dwyl/workshop/assets/194400/793f8f7e-64f4-4f90-a406-5550531cbfee)

Here's the sketch I made a few days ago:
![image](https://github.com/dwyl/workshop/assets/194400/69a3bc66-2c03-49f7-a7d3-3faffdab5028)

I don't have time to CAD-sketch this right now.
Time-crunched for Sunroom Build: https://github.com/dwyl/sunroom/issues/6

**Comment by nelsonic** [comment]
Ready to laser:
![image](https://github.com/dwyl/workshop/assets/194400/7f871300-2ec1-4172-b328-060cde511d65)

**Comment by nelsonic** [comment]
Im satisfied that this prototype works:
![IMG_1366](https://github.com/dwyl/workshop/assets/194400/94cee9a2-25ac-4681-afa7-e5563045b343)

![IMG_1367](https://github.com/dwyl/workshop/assets/194400/c2364eb8-6d22-4713-af9c-8163ae2b1083)


if I was to make it again, I would use **_two_ cableties**… 💭
Let’s see how long it lasts with one. 🤞🏼
