### ISSUE TITLE
Bug: Fridge Door `Sharpie` Pen Holder

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#132]
At present we don't have a clear [***`System`***](https://github.com/dwyl/home/issues/113) for writing things on containers that go in the Fridges. 🤷‍♂️ 
We are constantly have to hunt for a **`Sharpie`** when we want to write on a container (they keep disappearing) ... ⏳ 🔍 
This is such a time-suck and means people often don't bother to write on containers which creates _chaos_. 😖 

# Todo 

+ [x] Measure the `Sharpie` and `Magnet` we have. (see below)
+ [x] Create a purpose-built pen-holder 
+ [x] Should attach to the fridge door using ***`Magnets`***.
+ [x] Should _not_ require _any_ effort to remove or return the pen (i.e. not tight fitting)
+ [x] Should have space for 3 sharpie pens; backup of the backup! 😉 
+ [x] Should use _free_ "scrap" **`10mm` plywood** and be easy to laser-cut & assemble
+ [x] Should **_minimise_ materials** so that the **`Magnet`** is **_not_ overloaded**. 
+ [x] Design in `LigthBurn` #44
+ [x] Cut on `laser`
+ [x] Assemble
+ [ ] Finish with varnish for durability (wet hands) and ease of keeping clean.
+ [x] Buy bulk sharpies so we don't have to hunt for them.
  > **Note**: Already Ordered a 24-pack of `Sharpies` on Thursday, they should arrive on Wednesday next week (no Prime...)
  <img width="938" alt="sharpie-amzn-order" src="https://github.com/dwyl/workshop/assets/194400/a13b47fc-1a01-4c04-a5dd-11c320572b76">

Proposed Copy:
```
Please always write the
contents, date & name
on all storage containers
using the Sharpie provided.
And return the Sharpie. 
Thanks!
```

Feels like this is any _easy_ problem to solve _systematically_. 

# Relevant Measurements 

Sharpie length **`~140mm`** (_exactly_: **`137mm`**)
![image](https://github.com/dwyl/workshop/assets/194400/78b39028-6f27-42bc-826a-7bf92661a5cd)

Sharpie diameter at thickest: **`12mm`** (**`11.78mm`**):
![image](https://github.com/dwyl/workshop/assets/194400/6a56c85e-271f-4525-9387-b01b3c33698c)

Magnet diameter: **`19.5mm`**:
![image](https://github.com/dwyl/workshop/assets/194400/e82b7671-0508-4d4c-a596-082fea13daf7)

Magnet thickness: **`3.66mm`**: 
![image](https://github.com/dwyl/workshop/assets/194400/9cdba0cc-ab20-454e-ba09-c09678152ce2)

**Comment by nelsonic** [comment]
I'm _particularly_ keen on getting this done ***ASAP*** because I've heard people searching for **`Sharpies`** in the kitchen (which is within earshot of my desk) ***four*** times this week and it such a time-suck and distraction!! 😢

**Comment by nelsonic** [comment]
Revised copy:
```sh
Please always write 
the contents, 
date & person's name
on all storage containers
using the Sharpie 
and return it. Thanks!
```

**Comment by nelsonic** [comment]
Design in LightBurn:

![132-sharpie-holder-screenshot](https://github.com/dwyl/workshop/assets/194400/b72c50f2-a250-4259-99d8-a715c829b13c)

**Comment by iteles** [comment]
I really don't want to be a Debbie Downer on this but I think the problem is that people keep taking the black sharpie (the only one that works for writing on the glass containers we use in the freezer) OUT of the kitchen.
There is _already_ a specific place (a pen pot) where sharpies are kept in the kitchen, which is easy to use and placed right next to where the pyrexes on which we write on with them are used. 

If you feel the solution is to keep it on the fridge (like the other pen I have that I don't want to go walking - the one I use for marking off the 100 food's for A's introduction to solids 👶 ) we could just use the solution we already have for that pen too (note these are purposefully kept at an angle so the ink doesn't dry up):

![signal-2023-09-16-161157](https://github.com/dwyl/workshop/assets/4185328/47be5360-62d9-4847-ba51-2a7dce9de54a)

If you want to create a holder for the _chalk pens_ I use for the fridge meal planning board, now THAT would be ace (because there are multiples, this solution above doesn't work)!

**Comment by nelsonic** [comment]
@iteles removing a pen from the grip of a **`peg`** is a **2-handed operation** for **_most_ people**. 2️⃣ ✋ 
And _clearly_ this isn't working. `else` I wouldn't have had to hear about it 4 times this week ... 🙉 
This should be a single-handed operation so that the person already _holding_ the container
doesn't need to put it _down_ to get the pen and can just use it in the "flow" of putting it away.

And ... as noted in the OP. I ordered 

# 24 Pens

from amazon when I got sick of hearing about the pen going missing. 

_You_ are very welcome to use the tools in our - what many would consider a decently equipped - Workshop to create _anything_ you can imagine to solve _any_ problem systematically. 👌

**Comment by nelsonic** [comment]
Copy V3:
```md
Please use this Sharpie to write name, date and contents
on food containers, then return it. Thanks!
```

The only [Debbie] _Downer_ is not having a _system_ that _everyone_ can follow 
and then _me_ the person trying to write code having to hear about the missing pens. 💸 
Breaking the concentration of someone who's time is more valuable to the organisation than a thousand pens,
should be a "sackable offence". But it's not because _nobody_ cares if I get my work done.

**Comment by iteles** [comment]
You're only hearing about missing pens because I often find them/some in the workshop 😆 So I was just wondering if you had found any extra ones down there lately that I could use.

Anyway, I hear you on the one-handed operation.

What you're actually saying is that you should cancel your order for 24 sharpies and replace that with an order for ***clickable*** sharpies 😉 👍 
https://www.amazon.es/-/pt/dp/B0014GYMN0/
<img width="1298" alt="image" src="https://github.com/dwyl/workshop/assets/4185328/b46abf52-f4cd-4b79-abf9-bbee8449b392">

**Comment by nelsonic** [comment]
This might be the smallest font I’ve ever lasered (size 5mm) and it _appears_ to be working ok:

![IMG_0312](https://github.com/dwyl/workshop/assets/194400/bae2ee06-161a-4751-a5d4-ff1775fc8e69)

**Comment by nelsonic** [comment]
Simplified to 
![IMG_0316](https://github.com/dwyl/workshop/assets/194400/75a06208-ed66-4d47-882b-a4ab39fb436c)
horizontal pen holder. 
![IMG_0315](https://github.com/dwyl/workshop/assets/194400/6e82f74d-edc7-4992-89eb-a7058601f04d)

**Comment by nelsonic** [comment]
@iteles if you want the (nearly double the price) clicking Sharpie pens please go ahead and order them. I will keep the “classic” ones; which I’m very used to uncapping and writing with single-handed. 👌

**Comment by iteles** [comment]
Works great 👌🏻

**Comment by nelsonic** [comment]
Oh Wow, it's **`€28.97`** for **`12`**. that's **`€2.41/pen`**. 😮 
Compared to **`€17.93`** for **`24`**; **`€0.74/pen`** 👍 
so _more_ than ***TRIPPLE*** the price per pen!!  💸 
They would have to be quite a _lot_ better to justify that price jump. IMO. 💭

**Comment by nelsonic** [comment]
I didn't varnish the holder because I kinda lost interest. 😞 
But FYI: It took me _less_ time **`build`** the prototype than it did you to _write_ the comment. 🪚 💬 ⏳

**Comment by iteles** [comment]
Oh yea, they're ridiculous, I'd never buy them. Hence the wink 😉
