### ISSUE TITLE
`IPE 80` beam concrete plugs

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#139]
We are using `IPE 80` for the Aft Deck beams.
There are 19 beams protruding from the slab.
We need 2 plugs for each beam and they need to be snug!

# Todo

+ [x] Measure the `IPE 80` profile precisely. 
+ [x] Transfer measurements to `LightBurn` #44 
+ [x] Design the plugs
+ [x] Laser cut using scrap `10mm` plywood
+ [x] Test!!

**Comment by nelsonic** [comment]
Measured and created the template in `LightBurn`:
![image](https://github.com/dwyl/workshop/assets/194400/6679bc2c-769b-434e-a2be-f1ef103e6c11)

**Comment by nelsonic** [comment]
Gonna do a test cut now. ⚡

**Comment by nelsonic** [comment]
Cutting V1 Prototype:
![image](https://github.com/dwyl/workshop/assets/194400/10fab2b8-7c93-4987-947f-86ca3df102d3)

Testing the V1:
![image](https://github.com/dwyl/workshop/assets/194400/0873fc89-d9d1-4e87-a500-7cdc9ce79e8c)
Obvs didn't work.

V2: 
![image](https://github.com/dwyl/workshop/assets/194400/2e29a009-17bf-4471-a69d-69759bc01a97)

Works:
![image](https://github.com/dwyl/workshop/assets/194400/d8cd185c-e97a-47de-a52c-d149dc53acd9)

Tested in the concrete form:
![image](https://github.com/dwyl/workshop/assets/194400/3c80233b-b8cf-444a-bb36-8a8f85a658b9)

Not a great photo cause it's dark outside. 🌃 
But I'm confident this will work so going to print the 38 I need so I can assemble + glue them ready for mounting tomorrow.

**Comment by nelsonic** [comment]
Closing as done. _Obviously_ M decided that they "weren't needed" despite me asking him to install them all. 
Getting a bit old when you ask some you're _paying_ good money to do something _easy_ and well-defined
and they disrespectfully don't do it. 🤦‍♂️ 

My _next_ crew will follow my precise instructions to the _letter_. ✅
