### ISSUE TITLE
Welding & Metalwork Storage Station ⚡ 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#140]
At present the welding gear sits on the floor, the rods on the table and mask, gloves and apron on any other surface ... it's super lame. 🤦‍♂️ 

# Todo

+ [x] Measure Welding Rods: **400mm**
+ [x] Measure welding machine & cables so they can be neatly tucked away when not in-use.
+ [x] Build basic shelf to house all components on the west (road-side) wall. 
+ [x] Mount to the wall. 
+ [ ] Cable Management!

**Comment by nelsonic** [comment]
For anyone reading this, the _reason_ I'm prioritising this work to organise the Welding + Mettle Work area is simple:
having all the tools tidy and within easy reach will significantly improve efficiency/speed.
Going to be doing a _lot_ of welding for Bunk Beds in the near future and need a tidy/organised workspace to avoid chaos!

**Comment by nelsonic** [comment]
Prepared the second (final) shelf but haven’t had time to mount it yet … will do that tomorrow and a bit more tidying … 🤞🏼

**Comment by nelsonic** [comment]
A bit more progress this week:

![image](https://github.com/dwyl/workshop/assets/194400/1c4565e3-a8b0-4a94-ac73-8afcf1a1e1e3)

Will finish it off in the new year. 🤞

**Comment by nelsonic** [comment]
Minor progress this morning before the kids woke up:
![IMG_9825](https://github.com/dwyl/workshop/assets/194400/1e8ef418-daab-46b0-9eb7-b165084ef99c)

more in the new year…. 🤞🏼

**Comment by nelsonic** [comment]
Finished the welding table in the first week of Jan:

![image](https://github.com/dwyl/workshop/assets/194400/ec75a958-1350-4205-b55a-3800c9eb14c6)

But still have to do the cable tidying ... ⏳ 
Will get it done _soon_.

**Comment by nelsonic** [comment]
The welding station & storage has been working well this past year.
It's been re-built once because the first iteration wasn't strong enough and buckled when someone stood on it!
But since the re-build last summer it's been working well. 
Just wish we had (a lot) more space!
Closing for now as no further action required. ✅
