### ISSUE TITLE
Storage Box (Laser-cut. Hand-assembled + Finished) 📦 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#147]
Need to build a sturdy plywood box of `10mm` ply to store various items. 

Features (should):

+ [ ] Fit an `A4` sheet of paper with some space around. 210 x 297 mm -> 220 x 310 mm
+ [ ] Exterior Height: `150mm`
+ [x] Prevent dust from entering (lid should form a reasonably tight seal
+ [x] Built-in hinge (like on the https://github.com/nelsonic/vinyl-record-carry-storage-box ) 
+ [x] No handles required

**Comment by nelsonic** [comment]
Photos of finished box:

![IMG_9347](https://github.com/dwyl/workshop/assets/194400/87f8f79b-924e-4c6c-b6d0-56afc2f77d7f)
![IMG_9356](https://github.com/dwyl/workshop/assets/194400/daba01a4-ccd0-4cd8-89bb-10acae57a6a5)
![IMG_9357](https://github.com/dwyl/workshop/assets/194400/f598a8f9-d9b0-4029-9330-d3f8157dfdca)
![IMG_9358](https://github.com/dwyl/workshop/assets/194400/60552b49-1d43-4ccc-a6ed-92a5e0bcf5a9)

gave it to the inscribed person was an Xmas gift today.
They liked it a lot. Even though it was only a prototype, the effect was good. Will improve the design for next year. 👌

cc: @LuchoTurtle

**Comment by nelsonic** [comment]
Glad I made the effort to make this. Don't know if he _uses_ it. Will have another iteration this year. 
Closing for now as no further action required. ✅
