### ISSUE TITLE
AV Receiver Shelf

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#157]
At present our AV receiver is sitting on its side on the floor of the leisure room:

![IMG_9220](https://github.com/dwyl/workshop/assets/194400/e0d0f450-1bf6-493f-b788-07dcf05ebce2)

it’s untidy, looks bad and crucially makes it difficult to clean that area. So … I want to build a shelf to contain all the components and make it nice and tidy. 

# Todo

- [ ] measure all the components 📏
- [ ] Determine if we can make a super sturdy box shelf that can serve as additional seating 💭
- [ ] sketch the shelf 💡 
- [ ] Prepare cutting list 📝 
- [ ] Cut the pieces 🪚 
- [ ] Drill mounting holes 🕳️ 
- [ ] Weld the metal parts 🧑‍🏭
- [ ] Weld plates for mounting wooden shelves ⚡️
- [ ] Cut wood shelves to size 🪚 
- [ ] mount wood panels

@iteles the home cinema system cost us a decent chunk of cash in 2019 and has since gone up in price! 📈
**Question**: should the cabinet for the system be lockable? it would still be operated using the remote control without unlocking it, so anyone can _use_ it, they just cannot _remove_ it from the premises… 🙅‍♀️
Or is that a slippery slope considering how many *other* high value + easy-to-take tools we have in the workshop/office/ etc … 💭

# Why do this _now_?

Work outside has halted due to rain. 🌧️ 😢⏳
if we can _finish_ the leisure room, we could make it the new music & games room for everyone and everything would have a designated place and it could be super tidy and a nice place to be. 💭

I don’t consider it to be “high priority”, but if it was ***done*** then it would be done and we wouldn’t have to look at clutter in this room anymore. 🤞🏼

**Comment by nelsonic** [comment]
@iteles sadly, it cannot be in the corner out-of-the-way because of where the speaker cables terminate. 🙃 
But to maximise the "cleanability" going to wall-mount with a 12cm gap underneath. 📏 
OK to proceed with sketch? 📝
