### ISSUE TITLE
Toddler Toilet Training Throne™

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#81]
For context, please watch this: https://vimeo.com/121200116 **`T12m`**

# Wh? / What?

My mission is to make a **Toddler Toilet Step _with_ Side-handles** to aid our son in his toilet independence.
He knows the adults use the "real" toilet and is often fussy about using his 
**`IKEA LOCKIG Children's potty`** https://www.ikea.com/pt/en/p/lockig-childrens-potty-white-green-60193128/

![image](https://user-images.githubusercontent.com/194400/195383669-6b3145a0-d1f9-46c9-a824-9ee4a2397b25.png)

The plastic potty is very much a _temporary_ training environment and will _inevitably_ need to be phased out sooner or later. 
So I'm _proactively_ going to _make_ him a **Toddler Toilet Training Step** that will promote his independence. ASAP.

# Todo

+ [ ] Photograph and Measure the toilets we have [**`@home`**](https://github.com/dwyl/home/) 📸 
+ [ ] Measure the height of the first step of his **`Learning Tower`** for an ergonomics reference. 📏 
+ [ ] Sketch a simple version that includes a step and side handles. ✍️ 
+ [ ] Transfer sketch to **`LightBurn`**. Should use: 💻 
  + [ ] **`10mm birch plywood`** (our **`GOTO`** prototyping material) 🌲 
  + [ ] Cutout non-functional material to reduce weight while still preserving structure/stability/strength ✂️ 
  + [ ] Interlocking joints similar to the Vinyl Storage Box:  📦 
https://github.com/nelsonic/vinyl-record-carry-storage-box/issues/1#issuecomment-1156643677
  + [ ] QR Code on base for easy lookup 📱 
+ [ ] Cut the prototype on the Laser ⚡ 
+ [ ] Assemble + Glue the pieces 🔨 
+ [ ] Sand all the rough edges 🥪 
+ [ ] Fill in any material gaps. 💄 
+ [ ] Paint with **`White`** **`#FFFFFF`** primer 🧑‍🎨 
+ [ ] Paint with Color! 🌈 [TBD!] but we have all the colors of eco paints in the workshop! 🦄 
    see:  https://github.com/dwyl/home/issues/181#issuecomment-1006514705 [⚠️ Warning contains lots of high-res images!]

I'm budgeting **`T2h`** for this mini-project but it will probably roll into **`T4h`** if I'm too tired to focus ... let's see. 🤞

**Comment by nelsonic** [comment]
As much as I wanted to build this, I never found (made) the time. ⏳ 😞 
This is the `IKEA` _Plastic_ solution we ended up with:

![image](https://github.com/dwyl/workshop/assets/194400/8461de27-d3bb-4993-97e4-c562e5d7c406)


because nobody `else` was keen on _making_ a _wooden_ throne from first principals ... 💡 🏗️ 😍 
Our son manages fine. And now he would be _unlikely_ to switch as he is a creature of habit. 💭 

Most importantly, if this is what _other_ people use - because it's _cheap_ - 
then it would be an _up-hill_ battle to convince them to spend `€100` on a wooden one.
Though there _is_ a market for the Tripp Trapp® Chair: 

https://www.stokke.com/EUR/en-pt/high-chairs/tripp-trapp/1001.html
<img width="1482" alt="image" src="https://github.com/dwyl/workshop/assets/194400/01c2f3b5-7bab-40f5-aadb-a70c5baee3d4">

We have _two_ of them! Obvs purchased second-hand cause `€259` is _lol_! 💸 
But it shows that there is a market for high quality/durable ergonomic items for toddlers.
