### ISSUE TITLE
Emergency Exit Sign [Cover]

### ISSUE THREAD

**Issue by nelsonic** [dwyl/workshop#83]
The **`Emergency Exit`** Signs [**`@home`**](https://github.com/dwyl/home) have an **`LED`** status light that emits a **_super_ bright light** all day. 💡 
This is _fine_ during the day and ignorable in _most_ rooms, but in the ***bedrooms*** the light affects my sleep. 😩 
Yes, this might make me sound like a "snowflake" ... but there is peer-reviewed rigorous science to back me up here.
Here's an accessible article on the topic:
https://www.npr.org/sections/health-shots/2022/04/01/1089997121/light-disrupts-sleep

Soooo my plan is to create a sign that covers the super-bright status light 
but allows the actual emergency light to shine through when illuminated. 
i.e: still works if the smoke/fire alarm is triggered. 

# Todo

+ [x] Measure the signs
+ [x] Create a design prototype using 9mm OSB (our cheapest high density material)
+ [x] Cut it on the laser
+ [x] Assemble: glue + tacks
+ [x] Wait for glue to dry ... ⏳ 
+ [x] _Test_ it!

Note: the _reason_ this is **`P1`** is that it affects my sleep quality which means I'm _useless_ at everything `else`! 😩 
Fall asleep with a sleep mask. But when I wake up my eyes are uncovered and burning from the light. 😢 
Yes, again, this might make me sound like a "snowflake" ❄️  ... but these are the facts. 🤦‍♂️

**Comment by nelsonic** [comment]
Sign measured:

![77ECB382-A5C3-4ADA-B157-80DE2FC82A62](https://user-images.githubusercontent.com/194400/196014212-2c110d2a-507e-4a81-9971-7a4dace95d37.jpeg)

**Comment by nelsonic** [comment]
Basic:
![image](https://user-images.githubusercontent.com/194400/196015563-a8918603-6dc0-476b-9451-e03a9c830964.png)

**Comment by nelsonic** [comment]
Closing as this has been working adequately. 
Will remove it completely before we open the house to friends/guests.
